#!/bin/sh

TITLE=$1
OP=$2

echo "running for: $TITLE, operation $OP"
echo "wmctrl -l | grep -w "$TITLE" | tr -s ' ' | cut -d' ' -f1"
WINDOW_ID=`wmctrl -l | grep -w "$TITLE" | tr -s ' ' | cut -d' ' -f1`

echo "window id: $WINDOW_ID"

if [ "$OP" = "on" ]; then
  WMCTRL_OP="add"
  MOT_W_HINTS="0x2, 0x0, 0x0, 0x0, 0x0"
elif [ "$OP" = "off" ]; then
  WMCTRL_OP="remove"
  MOT_W_HINTS="0x2, 0x0, 0x1, 0x0, 0x0"
fi

wmctrl -r "$TITLE" -b "$WMCTRL_OP,above,skip_taskbar"
xprop -id $WINDOW_ID -f _MOTIF_WM_HINTS 32c -set _MOTIF_WM_HINTS "$MOT_W_HINTS"
